apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
  namespace: regiona
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: tb-edge
            - name: POSTGRES_PASSWORD
              value: postgres
          image: postgres:12
          name: postgres
          ports:
            - containerPort: 5432
          resources: 
            limits:
              cpu: "500m"
              memory: "128Mi"
            request:
              cpu: "250m"
              memory: "64Mi"
      restartPolicy: Always
status: {}
